### ISSUE TITLE
Confirmation email not sent when subscriber is already confirmed

### ISSUE THREAD

**Issue by bramley** [phpList/phplist-plugin-invite#1]
The plugin appears to be affected by a recent change to avoid sending a confirmation email when the subscriber is already confirmed, mantis https://mantis.phplist.com/view.php?id=17513
The problem was reported in the user forum https://forums.phplist.com/viewtopic.php?f=15&t=42103&p=104616

As a subscriber must be confirmed in order for the invite message to be sent, that change will stop the confirmation email from being sent. Possibly subscribers need to be marked unconfirmed as well as blacklisted when they are invited.

**Comment by michield** [comment]
hmm, yes, that needs attention

**Comment by ecoadmin** [comment]
Ok, but will it get it? This should be a GREAT plugin and would love to get it set up on my system. (ver 3.0.12)

**Comment by bramley** [comment]
This problem has been raised again on the forums https://discuss.phplist.org/t/invite-plugin-confirmationurl-doesnt-work/177
The problem isn't only that the confirmation email is not sent, but more importantly the subscriber remains blacklisted.

**Comment by michield** [comment]
this was fixed here https://github.com/phpList/phplist3/commit/96234a068ce219bb96a88965554cf22a057ecab9 but needs a new version. I will try to wrap up a new version asap.

**Comment by zSeriesGuy** [comment]
I'm relatively new to PHP and PHPList and don't really know what I'm doing.
What seems to have worked for me is to unconfirm the recipient.
I added this line of code after line 108 in inviteplugin.php.
Sql_Query(sprintf('update %s set confirmed = 0 where id = %d',$GLOBALS['tables']['user'],$userdata['id']));

This unconfirms the recipient right after the blacklisting.
Then when the recipient clicks on the confirmationurl, they get confirmed and unblacklisted.
Don't see the welcome message though.

**Comment by michield** [comment]
yes, that hack will work for now.

**Comment by RobbyZ** [comment]
This seems to no longer be a bug in recent versions of phplist; possibly close?

**Comment by bramley** [comment]
Fixed (a long time ago) by https://github.com/phpList/phplist-plugin-invite/pull/3
